-- GABRIEL MENDES CIRILLO RM:98214
-- LUCAS MONTE VERDE RM:551604

SET SERVEROUTPUT ON;

CREATE TABLE CONTRIBUINTE (
    ID_CONTRIBUINTE NUMBER PRIMARY KEY,
    NOME_CONTRIBUINTE VARCHAR2(20),
    SALARIO_BRUTO NUMBER,
    ALIQUOTA NUMBER,
    VALOR_DESCONTO NUMBER,
    SALARIO_LIQUIDO NUMBER
);
 
INSERT INTO CONTRIBUINTE (ID_CONTRIBUINTE, NOME_CONTRIBUINTE, SALARIO_BRUTO, ALIQUOTA, VALOR_DESCONTO, SALARIO_LIQUIDO)
VALUES (1, 'Antonio', 1500, NULL, NULL, NULL);
INSERT INTO CONTRIBUINTE (ID_CONTRIBUINTE, NOME_CONTRIBUINTE, SALARIO_BRUTO, ALIQUOTA, VALOR_DESCONTO, SALARIO_LIQUIDO)
VALUES (2, 'Simone', 2000, NULL, NULL, NULL);
 
INSERT INTO CONTRIBUINTE (ID_CONTRIBUINTE, NOME_CONTRIBUINTE, SALARIO_BRUTO, ALIQUOTA, VALOR_DESCONTO, SALARIO_LIQUIDO)
VALUES (3, 'Vanessa', 3000, NULL, NULL, NULL);
 
INSERT INTO CONTRIBUINTE (ID_CONTRIBUINTE, NOME_CONTRIBUINTE, SALARIO_BRUTO, ALIQUOTA, VALOR_DESCONTO, SALARIO_LIQUIDO)
VALUES (4, 'Guilherme', 4000, NULL, NULL, NULL);
 
INSERT INTO CONTRIBUINTE (ID_CONTRIBUINTE, NOME_CONTRIBUINTE, SALARIO_BRUTO, ALIQUOTA, VALOR_DESCONTO, SALARIO_LIQUIDO)
VALUES (5, 'Marco', 7000, NULL, NULL, NULL);
 
 
DECLARE
  V_ID_CONTRIBUINTE NUMBER;
  V_SALARIO_BRUTO NUMBER(7,2);
  V_ALIQUOTA NUMBER;
  V_VALOR_DESCONTO NUMBER(7,2);
  V_SALARIO_LIQUIDO NUMBER(7,2);
BEGIN
  V_ID_CONTRIBUINTE := &V_ID_CONTRIBUINTE;
  SELECT SALARIO_BRUTO INTO V_SALARIO_BRUTO FROM CONTRIBUINTE WHERE ID_CONTRIBUINTE = V_ID_CONTRIBUINTE;
  IF V_SALARIO_BRUTO <= 1637.11 THEN
    V_ALIQUOTA := 0;
    V_VALOR_DESCONTO := 0;
  ELSIF V_SALARIO_BRUTO <= 2453.50 THEN
    V_ALIQUOTA := 7.5;
    V_VALOR_DESCONTO := 122.78;
  ELSIF V_SALARIO_BRUTO <= 3271.38 THEN
    V_ALIQUOTA := 15;
    V_VALOR_DESCONTO := 306.80;
  ELSIF V_SALARIO_BRUTO <= 4087.65 THEN
    V_ALIQUOTA := 22.5;
    V_VALOR_DESCONTO := 552.15;
  ELSE
    V_ALIQUOTA := 27.5;
    V_VALOR_DESCONTO := 756.53;
  END IF;
  V_SALARIO_LIQUIDO := V_SALARIO_BRUTO - V_VALOR_DESCONTO;
  UPDATE CONTRIBUINTE
  SET ALIQUOTA = V_ALIQUOTA,
      VALOR_DESCONTO = V_VALOR_DESCONTO,
      SALARIO_LIQUIDO = V_SALARIO_LIQUIDO
  WHERE ID_CONTRIBUINTE = V_ID_CONTRIBUINTE;
  DBMS_OUTPUT.PUT_LINE('CONTRIBUINTE ID: ' || V_ID_CONTRIBUINTE);
  DBMS_OUTPUT.PUT_LINE('SALÁRIO BRUTO: R$ ' || V_SALARIO_BRUTO);
  DBMS_OUTPUT.PUT_LINE('ALÍQUOTA: ' || V_ALIQUOTA || '%');
  DBMS_OUTPUT.PUT_LINE('VALOR DO DESCONTO: R$ ' || V_VALOR_DESCONTO);
  DBMS_OUTPUT.PUT_LINE('SALÁRIO LÍQUIDO: R$ ' || V_SALARIO_LIQUIDO);
END;
/

-- GABRIEL MENDES CIRILLO RM:98214
-- LUCAS MONTE VERDE RM:551604